spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_PUBLIC_URL}
    username: ${PGUSER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: delete
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

